config/routes.rb
Rails.application.routes.draw do
  root 'home#home'
  resources :members
end

app/models/member.rb
class Member < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def home
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  def new
    @member = Member.new
  end

  def create
    @member = Member.new(member_params)
    if @member.save
      flash[:success] = "Got it!"
      respond_to do |format|
        format.html { redirect_to new_member_path }
      end
    else
      flash[:error] = "Whoops! Something went wrong..."
      respond_to do |format|
        format.html { redirect_to new_member_path }
      end
    end
  end

  def member_params
    params.require(:member).permit(:name, :twitter, :email, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/home.html.erb
<section class="m-section__landing_page">
  <%= link_to new_member_path do %>
    <input type="submit" class="btn btn-main" value="Join">
  <% end %>
  <%= link_to members_path do %>
    <input type="submit" class="btn btn-main" value="Commnunity" >
  <% end %>
</section>

app/views/info/_about.html.erb
<section class="m-section__about_part1">
  <section class="m-section__underlay"></section>
  <div class="intro-header">
    <div class="container">
      <div class="row" style="padding-bottom:0;">
        <div class="intro-message">
          <h1>we are blhackathon</h1>
          <hr class="section-heading-spacer-alt">
        </div>
      </div>
    </div>
  </div>
  <div class="content-section-a">
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-sm-push-2 col-sm-8">
          <p class="lead">
            Blhackathon wants to provide you with a community where you can feel free to nerd out, geek out, be wonderfully weird and excited about building stuff.
            A space free of judgment, and full of creativity, pedagogy, and collaboration.
            A place where egos are left outside, and positivity takes over.
            It is an opportunity to be yourself, and get to know like-minded individuals while collaborating on interesting projects.
          </p>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/layouts/_footer.html.erb
<!-- Footer -->
<footer class="l-footer">
  <div class="container">
    <div class="col-lg-12">
      <ul>
        <li class="copyright text-muted small"> <a> Team </a> </li>
        <span class="copyright text-muted small">|</span>
        <li class="copyright text-muted small"> <a> FAQ </a> </li>
        <span class="copyright text-muted small">|</span>
        <li class="copyright text-muted small"> <a> Contact Us </a> </li>
      </ul>
    </div>
    <div class="col-lg-12">
      <p class="copyright text-muted small">Copyright &copy; Blhackathon 2016. All Rights Reserved</p>
    </div>
  </div>
</footer>

app/views/layouts/_nav.html.erb
<!-- Navigation -->
<nav class="navbar navbar-default topnav" role="navigation">
  <div class="container topnav">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <a class="navbar-brand topnav" href="/"><span>#</span>BLHACKATHON</a>
      <div class="m-social">
        <ul class="m-social__buttons">
          <li>
            <a href="https://twitter.com/blhackathon"><%= fa_icon "twitter", class: "m-social__button" %></a>
          </li>
          <li>
            <a href="https://www.facebook.com/blhackathon/"><%= fa_icon "facebook", class: "m-social__button" %></a>
          </li>
          <li>
            <a href="https://www.instagram.com/blhackathon/"><%= fa_icon "instagram", class: "m-social__button" %></a>
          </li>
        </ul>
      </div>
    </div>
  </div>
  <!-- /.container -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>THE BLHACKATHON</title>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <meta name="viewport" content="width=device-width">
  <meta name="viewport" content="width=device-width">
  <link href='https://fonts.googleapis.com/css?family=Titillium+Web' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Russo+One' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all'%>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, class: "flash-#{name}" %>
  <% end %>
  <%= render 'layouts/nav' %>
  <%= yield %>
  <%= render 'layouts/footer' %>
</body>
</html>

app/views/members/new.html.erb
<!-- Member form -->
<div class="m-section__idea_form">
  <div class="container">
    <div class="row">
      <!-- FORM -->
      <div class="col-md-8 col-lg-8 m-section__idea_form__intro-form-box col-lg-offset-6">
        <h1>Join</h1>
        <%= form_for @member do |f| %>
        <div class="row control-group">
          <div class="form-group col-xs-12 floating-label-form-group controls">
            <%= f.text_field :name, placeholder: "Name", class: "form-control" %>
          </div>
        </div>

        <div class="row control-group">
          <div class="form-group col-xs-12 floating-label-form-group controls">
            <%= f.text_field :email, placeholder: "Email Address", class: "form-control" %>
          </div>
        </div>

        <div class="row control-group">
          <div class="form-group col-xs-12 floating-label-form-group controls">
            <%= f.text_field :twitter, placeholder: "Twitter", class: "form-control" %>
          </div>
        </div>

        <div class="row control-group">
          <div class="form-group col-xs-12 floating-label-form-group controls">
            <%= f.text_area :bio, placeholder: "A little about you", class: "form-control" %>
          </div>
        </div>

        <br>
        <div class="row">
          <div class="form-group col-xs-12">
            <%= f.submit "Submit", class: "btn btn-block btn-md btn-lg" %>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>